# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CD

on:
  push:
    branches: [ master ] 

jobs:
  deploy:
    name: Deploy to Build
    runs-on: ubuntu-latest 

    steps:
    
    # Prereqs
    - uses: actions/checkout@v2
    
    # Setup the node env
    - name: Setup the Node Env
      uses: actions/setup-node@v4
      with:
        node-version: '23'
     
    - name: install & gen 
      run: |
        npm ci --omit=optional
        npm run build

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env: 
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}